let all=[],queue=[],index=0,saved=JSON.parse(localStorage.getItem('krog-match-saved')||'[]'),activeFilter='all';
const $=id=>document.getElementById(id);const deck=$('deck'),progressText=$('progressText'),savedCount=$('savedCount');
function esc(s){return String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
function shuffle(a){a=[...a];for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
function priceText(p){const n={PRICE_LEVEL_FREE:0,PRICE_LEVEL_INEXPENSIVE:1,PRICE_LEVEL_MODERATE:2,PRICE_LEVEL_EXPENSIVE:3,PRICE_LEVEL_VERY_EXPENSIVE:4}[p];return Number.isInteger(n)&&n>0?'$'.repeat(n):'Pris okänt'}
function isOpen(p){return p.openNow===true}
function photoStyle(p){return p.photoName?`background-image:url('/api/photo?name=${encodeURIComponent(p.photoName)}')`:''}
function applyFilter(){queue=all.filter(p=>activeFilter==='all'||activeFilter==='open'&&isOpen(p)||activeFilter==='4.5'&&(p.rating||0)>=4.5||activeFilter==='budget'&&['PRICE_LEVEL_INEXPENSIVE','PRICE_LEVEL_MODERATE'].includes(p.priceLevel));queue=shuffle(queue);index=0;render()}
function cardHTML(p,behind=false){return `<article class="card ${behind?'behind':'front'}"><div class="stamp pass">PASS</div><div class="stamp like">SPARA</div><div class="photo" style="${photoStyle(p)}"></div><div class="card-copy"><div class="meta">${esc(p.type||'Restaurang')} · ${isOpen(p)?'ÖPPET NU':'STÄNGT/OKÄNT'}</div><h2>${esc(p.name)}</h2><div class="rating"><span class="star">★ ${p.rating?Number(p.rating).toFixed(1):'–'}</span><span>${p.userRatingCount?`${p.userRatingCount.toLocaleString('sv-SE')} omdömen`:''}</span><span>${priceText(p.priceLevel)}</span></div><div class="address">${esc(p.address||'Stockholm')}</div><div class="badge">Tryck i för mer info</div></div></article>`}
function render(){savedCount.textContent=saved.length;if(!queue.length){deck.innerHTML='<div class="empty">Inga krogar matchar filtret. Prova ett annat.</div>';progressText.textContent='0 krogar';return}if(index>=queue.length){deck.innerHTML='<div class="empty">Du har gått igenom den här mixen.<br><br>Tryck NY MIX för en ny ordning.</div>';progressText.textContent=`Klart · ${saved.length} sparade`;return}deck.innerHTML=(queue[index+1]?cardHTML(queue[index+1],true):'')+cardHTML(queue[index]);progressText.textContent=`${index+1} av ${queue.length}`;bindSwipe(deck.querySelector('.front'))}
function bindSwipe(card){let id=null,sx=0,x=0,lastX=0,lastT=0,vx=0,drag=false,raf=0;const pass=card.querySelector('.stamp.pass'),like=card.querySelector('.stamp.like');const paint=()=>{raf=0;const p=Math.min(Math.abs(x)/115,1),r=Math.max(-8,Math.min(8,x/28));card.style.transform=`translate3d(${x}px,0,0) rotate(${r}deg)`;if(x>0){like.style.opacity=p;pass.style.opacity=0}else{pass.style.opacity=p;like.style.opacity=0}};card.addEventListener('pointerdown',e=>{id=e.pointerId;drag=true;sx=lastX=e.clientX;lastT=performance.now();vx=0;card.classList.add('dragging');card.setPointerCapture?.(id)});card.addEventListener('pointermove',e=>{if(!drag||e.pointerId!==id)return;const now=performance.now(),dt=Math.max(8,now-lastT);x=e.clientX-sx;vx=vx*.7+((e.clientX-lastX)/dt)*.3;lastX=e.clientX;lastT=now;if(!raf)raf=requestAnimationFrame(paint)});const end=e=>{if(!drag||e.pointerId!==id)return;drag=false;card.classList.remove('dragging');const commit=Math.abs(x)>80||Math.abs(vx)>.45;if(commit){const dir=(Math.abs(vx)>.45?Math.sign(vx):Math.sign(x))||1;decide(dir>0?'like':'pass',card,dir)}else{card.classList.add('snap');card.style.transform='translate3d(0,0,0) rotate(0)';pass.style.opacity=like.style.opacity=0;setTimeout(()=>card.classList.remove('snap'),260);x=0}};card.addEventListener('pointerup',end);card.addEventListener('pointercancel',end)}
function decide(type,card=deck.querySelector('.front'),dir=type==='like'?1:-1){if(!card||index>=queue.length)return;const p=queue[index];if(type==='like'&&!saved.some(x=>x.id===p.id)){saved.push(p);localStorage.setItem('krog-match-saved',JSON.stringify(saved));savedCount.textContent=saved.length}card.classList.add('leaving');card.style.transform=`translate3d(${dir*Math.max(innerWidth,600)*1.2}px,-8px,0) rotate(${dir*10}deg)`;card.style.opacity=0;setTimeout(()=>{index++;render()},190)}
function openDetail(p){$('detailPhoto').style.cssText=photoStyle(p);$('detailMeta').textContent=`${p.type||'Restaurang'} · ${priceText(p.priceLevel)}`;$('detailTitle').textContent=p.name;$('detailRating').textContent=`★ ${p.rating?Number(p.rating).toFixed(1):'–'}  ·  ${p.userRatingCount||0} Google-omdömen`;$('detailAddress').textContent=p.address||'';$('detailHours').innerHTML=p.weekdayDescriptions?.length?'<b>Öppettider</b><br>'+p.weekdayDescriptions.map(esc).join('<br>'):'Öppettider saknas';$('mapsLink').href=p.googleMapsUri||'#';if(p.websiteUri){$('websiteLink').href=p.websiteUri;$('websiteLink').classList.remove('hidden')}else $('websiteLink').classList.add('hidden');$('detailSheet').classList.add('open')}
function showSaved(){const list=$('savedList');list.innerHTML=saved.length?saved.map(p=>`<div class="saved-item"><div class="saved-thumb" style="${photoStyle(p)}"></div><div><b>${esc(p.name)}</b><small>★ ${p.rating?Number(p.rating).toFixed(1):'–'} · ${priceText(p.priceLevel)}</small></div><a href="${esc(p.googleMapsUri||'#')}" target="_blank">↗</a></div>`).join(''):'<div class="empty">Inga sparade krogar ännu.</div>';$('savedSheet').classList.add('open')}
async function load(){deck.innerHTML='<div class="loading">Letar efter bra krogar i Stockholm…</div>';progressText.textContent='Hämtar krogar…';try{const r=await fetch('/api/restaurants',{cache:'no-store'});const d=await r.json();if(!r.ok)throw new Error(d.error||'API-fel');all=d.restaurants||[];applyFilter()}catch(e){deck.innerHTML=`<div class="empty">Kunde inte hämta restauranger.<br><br><small>${esc(e.message)}</small></div>`;progressText.textContent='Något gick fel'}}
$('passBtn').onclick=()=>decide('pass');$('likeBtn').onclick=()=>decide('like');$('infoBtn').onclick=()=>queue[index]&&openDetail(queue[index]);$('refreshBtn').onclick=()=>{queue=shuffle(queue);index=0;render()};$('savedBtn').onclick=showSaved;$('closeDetail').onclick=()=>$('detailSheet').classList.remove('open');$('closeSaved').onclick=()=>$('savedSheet').classList.remove('open');$('clearSaved').onclick=()=>{saved=[];localStorage.removeItem('krog-match-saved');showSaved();savedCount.textContent=0};document.querySelectorAll('.chip').forEach(b=>b.onclick=()=>{document.querySelectorAll('.chip').forEach(x=>x.classList.remove('active'));b.classList.add('active');activeFilter=b.dataset.filter;applyFilter()});load();