const FIELD_MASK=['places.id','places.displayName','places.formattedAddress','places.location','places.rating','places.userRatingCount','places.priceLevel','places.photos','places.primaryType','places.primaryTypeDisplayName','places.types','places.currentOpeningHours','places.websiteUri','places.googleMapsUri','places.reviews'].join(',');
const STARS={'frantzén':3,'aira':2,'aloë':2,'adam albin':1,'celeste':1,'dashi':1,'ekstedt':1,'ergo':1,'etoile':1,'nour':1,'operakällaren':1,'seafood gastro':1,'sushi sho':1};
const SELECTED=['woodstockholm','rolfs kök','babette','etoile','forma','celeste','black milk gastro bar','petri','ärla','essence','brasserie astoria','bar agrikultur','aira','lilla ego','frantzén','ekstedt','hillenberg','ergo','solen','seafood gastro','triton','oxenstiernan','freyja','leijontornet','minh mat','bord','prospero','nour','restaurang b.a.r.','farang','lux dag för dag','operakällaren','allegrine','nisch','ulla winbladh','matbaren','sushi sho','washoku tomo','dashi','voisine','persona','adam albin'];
const BIB=['babette','bar agrikultur','lilla ego','triton','ärla','matbaren','allegrine'];
const norm=s=>String(s||'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9åäöéü ]/gi,' ').replace(/\b(restaurang|restaurant|ristorante|stockholm|och|and|the)\b/g,' ').replace(/\s+/g,' ').trim();
const match=(name,target)=>{const n=norm(name),t=norm(target);return n===t||n.startsWith(t+' ')||n.endsWith(' '+t)};
function michelin(name){let stars=0;for(const [k,v] of Object.entries(STARS))if(match(name,k)){stars=v;break}const bib=BIB.some(k=>match(name,k));const selected=stars>0||bib||SELECTED.some(k=>match(name,k));return{stars,bib,selected}}
function hav(lat1,lng1,lat2,lng2){const R=6371000,r=x=>x*Math.PI/180,dlat=r(lat2-lat1),dlng=r(lng2-lng1),a=Math.sin(dlat/2)**2+Math.cos(r(lat1))*Math.cos(r(lat2))*Math.sin(dlng/2)**2;return 2*R*Math.asin(Math.sqrt(a))}
async function search(key,q,center,radius){const body={textQuery:q,pageSize:20,languageCode:'sv',regionCode:'SE',locationBias:{circle:{center:{latitude:center.lat,longitude:center.lng},radius:Math.min(Math.max(radius,500),50000)}}};const r=await fetch('https://places.googleapis.com/v1/places:searchText',{method:'POST',headers:{'Content-Type':'application/json','X-Goog-Api-Key':key,'X-Goog-FieldMask':FIELD_MASK},body:JSON.stringify(body)});const d=await r.json();if(!r.ok)throw new Error(d?.error?.message||`Google Places ${r.status}`);return d.places||[]}
function cuisine(types=[]){const j=types.join(' ').toLowerCase(),m=[['italian','Italienskt'],['japanese','Japanskt'],['sushi','Japanskt'],['french','Franskt'],['seafood','Fisk & skaldjur'],['scandinavian','Nordiskt'],['swedish','Svenskt']];for(const [k,v] of m)if(j.includes(k))return v;return j.includes('fine_dining')?'Fine dining':'Övrigt'}
function normalize(p,origin){const name=p.displayName?.text||'Okänd restaurang',m=michelin(name),distanceMeters=p.location?Math.round(hav(origin.lat,origin.lng,p.location.latitude,p.location.longitude)):null;return{id:p.id,name,address:p.formattedAddress||'',latitude:p.location?.latitude??null,longitude:p.location?.longitude??null,distanceMeters,rating:p.rating||null,userRatingCount:p.userRatingCount||0,priceLevel:p.priceLevel||null,photoName:p.photos?.[0]?.name||null,type:p.primaryTypeDisplayName?.text||'Restaurang',types:p.types||[],cuisine:cuisine(p.types||[]),openNow:p.currentOpeningHours?.openNow,weekdayDescriptions:p.currentOpeningHours?.weekdayDescriptions||[],websiteUri:p.websiteUri||null,googleMapsUri:p.googleMapsUri||null,menuSearchUri:`https://www.google.com/search?q=${encodeURIComponent(name+' '+(p.formattedAddress||'')+' meny')}`,reviews:(p.reviews||[]).slice(0,3).map(r=>({rating:r.rating||null,text:r.text?.text||r.originalText?.text||'',author:r.authorAttribution?.displayName||'Google-användare',time:r.relativePublishTimeDescription||''})).filter(r=>r.text),editorial:[],michelinStars:m.stars,michelinSelected:m.selected,michelinBib:m.bib,casual:m.bib,qualityScore:(p.rating||0)*10+Math.log10(Math.max(1,p.userRatingCount||0))*4+(m.selected?8:0)+(m.bib?10:0)+m.stars*15}}
export default async function handler(req,res){res.setHeader('Cache-Control','s-maxage=300, stale-while-revalidate=900');const key=process.env.GOOGLE_PLACES_API_KEY;if(!key)return res.status(500).json({error:'GOOGLE_PLACES_API_KEY saknas'});try{const lat=Number(req.query?.lat),lng=Number(req.query?.lng),rr=Number(req.query?.radius),has=Number.isFinite(lat)&&Number.isFinite(lng);const center=has?{lat,lng}:{lat:59.3293,lng:18.0686};const radius=has?Math.min(Math.max(Number.isFinite(rr)?rr:2000,500),20000):14000;const qs=['Michelin restauranger Stockholm','Michelin Guide restauranger Stockholm','Bib Gourmand Stockholm','Michelin star restaurant Stockholm'];const batches=await Promise.all(qs.map(q=>search(key,q,center,radius)));const seen=new Set();const rows=batches.flat().filter(p=>p.id&&!seen.has(p.id)&&seen.add(p.id)).map(p=>normalize(p,center)).filter(p=>p.michelinSelected).filter(p=>p.distanceMeters===null||p.distanceMeters<=radius).sort((a,b)=>(b.michelinStars-a.michelinStars)||(b.michelinBib-a.michelinBib)||(b.qualityScore-a.qualityScore));res.status(200).json({restaurants:rows.slice(0,50),search:{mode:has?'nearby':'stockholm',radiusMeters:radius,candidateCount:batches.flat().length,eligibleCount:rows.length}})}catch(e){res.status(500).json({error:e.message||'Kunde inte hämta Michelin-krogar'})}}
